From nginx
RUN mkdir /usr/share/nginx/html/app1
RUN mkdir /usr/share/nginx/html/app2
RUN mkdir /usr/share/nginx/html/app3
copy index.html /usr/share/nginx/html/app1
copy index.html /usr/share/nginx/html/app2
copy index.html /usr/share/nginx/html/app3