From nginx
RUN mkdir /usr/share/nginx/html/app1
RUN mkdir /usr/share/nginx/html/app2
RUN mkdir /usr/share/nginx/html/app3
copy index1.html /usr/share/nginx/html/app1
copy index2.html /usr/share/nginx/html/app2
copy index3.html /usr/share/nginx/html/app3
